name: CI
on:
  push:
    branches: [ "task/*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Package

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: publishHtmlTask
      run: |
        npm install
        sudo npm install -g tfx-cli semver

    - name: Prepare Task
      working-directory: publishHtmlTask
      run: |
        tsc
        mv task.dev.json task.json
        cp -r node_modules dist/

    - name: Rev Manifest
      run: |
        current_version=$(tfx extension show -t ${{ secrets.MarketplaceToken }} --publisher Farrellsoft --extension-id publish-html-task-dev --output json | jq '.versions | .[0].version')
        current_version=$(if [ $current_version == "null" ]; then echo "1.0.0"; else echo $current_version; fi)
        current_version=$(echo $current_version | sed -e 's/^"//' -e 's/"$//')
        new_version=$(semver -i $current_version)
        json=$(cat vss-extension.dev.json | jq --arg v "${new_version}" '.version = $v')
        echo $json > vss-extension.dev.json

    - name: Publish Extension
      run: |
        tfx extension publish -t ${{ secrets.MarketplaceToken }} --share-with Farrellsoft --manifests vss-extension.dev.json
